# Generated by Django 3.2.16 on 2023-04-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'managed': False},
        ),
    ]
